#Max Monsters (zombie,skeleton, creeper, etc.)
#Range: 1 ~ 210
monsterCap = 22
#MaxCreatures (sheep, cows)
#Range: 1 ~ 210
creatureCap = 2
#Max Ambient (bats)
#Range: 1 ~ 210
ambientCap = 1
#Max water creature (squid, dolphins)
#Range: 1 ~ 210
waterCreatureCap = 2
#Max Water Ambient (Tropical Fish)
#Range: 1 ~ 210
waterAmbientCap = 5
#Max Water Creature (Glow Squid)
#Range: 1 ~ 210
undergroundWaterCreatureCap = 1

